undercover-chat-format: '&8<&f%1$s&8> &f%2$s'
mymemory-translated-net-api-key: ''
google-maps-api-key: ''
max-slurp-range: 100
default-slurp-range: 16
xray-warn-time-millis: 900000
flykick-message: Flying is not enabled on this server
spamkick-message: Kicked for spamming
shortcuts:
  - replace: "^/iload\b"
    with: "/inv load"
  - replace: "^/isave\b"
    with: "/inv save"
  - replace: "^/ilist\b"
    with: "/inv list"
  - replace: "^/j\b"
    with: "/jump"