name: Root
main: wickersoft.root.Root
version: 3.1.4.1
api-version: 1.15
author: Wickersoft+Syndek
depend: ['WorldGuard']

commands:
  activity:
    description: Find out when to expect a player online
    permission: root.activity
    aliases: [root:activity]
  delmark:
    description: Removes a mark from a player
    permission: root.delmark
    aliases: [root:delmark]
  ding:
    description: Plays a "Ding" sound when a chat message matches the specified pattern
    permission: root.ding
    aliases: [root:ding]
  freeze:
    description: Freeze a player and stop them moving and using commands.
    permission: root.freeze
    aliases: [f, root:f, root:freeze]
  instantsign:
    description: Generates signs that can be played without editing
    permission: root.instantsign
    aliases: [sign, root:sign, root:instantsign]
  mark:
    description: Keep notes on a player
    permission: root.mark
    aliases: [root:mark]
  portal:
    description: "Creates, debugs or simulates Portals"
    permission: root.portal
    aliases: [root:portal]
  player:
    description: View information about a player
    permission: root.player
    aliases: [p, root:p, root:player]
  rtps:
    description: Continuously shows instantaneous TPS and tick times
    permission: root.rtps
    aliases: [root:rtps]
  seelwc:
    description: Highlights nearby blocks protected by LWC
    permission: root.seelwc
    aliases: [root:seelwc]
  shadowmute:
    description: Makes a player's messages only visible to that player
    permission: root.shadowmute
    aliases: [smute, root:smute, root:shadowmute]
  sub:
    description: Display subtitles after a player's messages
    permission: root.sub
    aliases: [root:sub]
  tesseract:
    description: Generate tesseracts
    permission: root.tesseract
    aliases: [root:tesseract]  
  undercover:
    description: Go undercover and hide your chat formatting.
    permission: root.undercover
    aliases: [u, root:u, root:undercover]
  uuid:
    description: Shows UUID, current and past names of a player.
    permission: root.uuid
    aliases: [root:uuid]
  volatile:
    description: Makes an item impossible to pick up for Players without a certain permission
    permission: root.volatile
    aliases: [root:volatile]
  wand:
    description: Adds special right-click actions to the item held
    permission: root.wand
    aliases: [root:wand]

permissions:
  root.*:
    description: Gives access to all features in Root.
    children:
      root: true
      root.activity: true
      root.chat.*: true
      root.delmark: true
      root.ding: true
      root.freeze: true
      root.item.*: true
      root.instantsign: true
      root.mark: true
      root.notify.*: true
      root.portal: true
      root.player.*: true
      root.rtps: true
      root.seelwc: true
      root.shadowmute.*: true
      root.sign.*: true
      root.sub: true
      root.tesseract: true
      root.undercover: true
      root.uuid: true
      root.volatile: true
      root.wand.*: true
      
  root.chat.*:
    children:
      root.chat: true
      root.chat.nodisconnectspam: true
  
  root.freeze.*:
    description: Gives access to the freeze feature of Root and its bypass.
    children:
      root.freeze: true
      root.freeze.bypass: true
        
  root.item.*:
    children:
      root.item.instantsign: true
      root.item.volatile: true
  
  root.notify.*:
    children:
      root.notify.firstjoin: true
      root.notify.flykick: true
      root.notify.iprec: true
      root.notify.mark: true
      root.notify.xray: true
      root.notify.xray.bypass: true
  
  root.player.*:
    children:
      root.player: true
      root.player.homes: true
      root.player.preciselocation: true
  
  root.sign.*:
    children:
      root.sign: true  
      root.sign.boat.*: true
      root.sign.cart.*: true
      root.sign.dice.*: true
      root.sign.info.*: true
      root.sign.launch.*: true
      
  root.sign.boat.*:
    children:
      root.sign.boat: true  
      root.sign.boat.create: true

  root.sign.cart.*:
    children:
      root.sign.cart: true  
      root.sign.cart.create: true
  
  root.sign.dice.*:
    children:
      root.sign.dice: true  
      root.sign.dice.create: true
  
  root.sign.info.*:
    children:
      root.sign.info: true  
      root.sign.info.create: true
      root.sign.info.edit: true
      
  root.sign.launch.*:
    children:
      root.sign.launch: true
      root.sign.launch.create: true
  
  root.sleep.*:
    children:
      root.sleep: true
      root.sleep.all: true
      root.sleep.other: true

  root.shadowmute.*:
    description: Gives access to the shadowmute feature of Root and its bypass.
    children:
      root.shadowmute: true
      root.shadowmute.see: true

  root.wand.*:
    children:
      root.wand: true
      root.wand.petowner: true
      root.wand.stack: true
      root.wand.strip.*: true
      root.wand.silkdick: true
  
  root.wand.strip.*:
    children:
      root.wand.strip: true
      root.wand.strip.player: true